apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: cluster
  name: cluster
spec:
  forProvider:
    network: "projects/pet-dev-sandbox/global/networks/crossplane-network"
    subnetwork: "projects/pet-dev-sandbox/regions/us-central1/subnetworks/crossplane-subnet"
    deletionProtection: false
    enableAutopilot: true
    enableIntranodeVisibility: true
    ipAllocationPolicy:
      - {}
    location: europe-north1
  writeConnectionSecretToRef:
    name: gke-managed-resources-kubeconfig
    namespace: crossplane-system
  
